import { MigrationInterface, QueryRunner, TableColumn } from "typeorm"

export class AddAutoGeneratedIdInUser1739671554308
	implements MigrationInterface
{
	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.changeColumn(
			"user",
			"id",
			new TableColumn({
				name: "id",
				type: "int",
				isPrimary: true,
				isGenerated: true,
				generationStrategy: "increment",
			}),
		)
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.changeColumn(
			"user",
			"id",
			new TableColumn({
				name: "id",
				type: "int",
				isPrimary: true,
			}),
		)
	}
}
