export const SERVER_ERROR_MESSAGE = "Oops! Something went wrong!"
export const REQUEST_USER_PAYLOAD_KEY = "REQUEST_USER_PAYLOAD_KEY"
export const REQUEST_TOKEN_PAYLOAD_KEY = "REQUEST_TOKEN_PAYLOAD_KEY"
export const IS_PUBLIC_ROUTER_KEY = "IS_PUBLIC_ROUTER_KEY"
export const TOTP_INTERVAL_IN_SECONDS = 30
export const TOTP_DIGITS = 6
